/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import com.tcs.tallerListas.beans.Estudiante;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;


public class IngresoEstudiantes {

	public static void main(String[] args) {

		System.out.println("################ Ingreso de estudiantes ################");
		List<String[]> estData = new ArrayList<>();
		List<Estudiante> estudiantes = new ArrayList<>();
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));

			while (data.hasNextLine()) {
				estData.add(data.nextLine().split(","));
			}
			for (int i = 0; i < estData.size(); i++) {
				estudiantes.add(new Estudiante(estData.get(i)[0],
						estData.get(i)[1],
						estData.get(i)[2],
						estData.get(i)[3]));
			}
			imprimir(estudiantes);
		} catch (FileNotFoundException e) {
			System.out.println("Ocurrió un error al obtener la información");
		}
	}

	public static void imprimir(List<Estudiante> estudiante) {
		System.out.println("Ingrese una opción 1. para ver el total de estudiantes \n" +
				"Ingrese una opción 2. para ver estudiantes entre 6 y 10 años \n" +
				"Ingrese una opción 3. para ver estudiantes por grado \n" +
				"Ingrese una opción 4. para ver estudiantes con identificador TI ");
		Scanner opciones = new Scanner(System.in);
		int opcion = opciones.nextInt();
		if (opcion == 1) {
			System.out.println("El total de estudiantes son: " + estudiante.size());
		} else if (opcion == 2) {
			System.out.println("El total de estudiantes entre 6 años y 10 son: " + contador(estudiante));
		} else if (opcion == 3) {
			imprimirPorGrados(estudiante);
		}else if (opcion == 4) {
			System.out.println("Estudiantes con TI en su identificación \n" );
			filtro(estudiante);

		}
	}
	public static void filtro(List<Estudiante> estudiante){
		for (int i = 0; i < estudiante.size(); i++) {
			if (estudiante.get(i).getId().contains("TI")){
				System.out.println("Edad: " + estudiante.get(i).getEdad() + "\n"
				+ "Grado: " + estudiante.get(i).getGrado());
				System.out.println("====================================================== \n");
			}
		}
	}

	public static void imprimirPorGrados(List<Estudiante> estudiante){
		System.out.println(separarPorGrados(estudiante).get(0).get(1));
		for (int i = 0; i < separarPorGrados(estudiante).size() ; i++) {
			for (int j = 0; j < separarPorGrados(estudiante).get(i).size(); j++) {
				System.out.println("Estudiantes del grado " + separarPorGrados(estudiante).get(i).get(j).getGrado() + "\n"
						+ separarPorGrados(estudiante).get(i).get(j).getId() + "\n" +
						separarPorGrados(estudiante).get(i).get(j).getNombre() + "\n" +
						separarPorGrados(estudiante).get(i).get(j).getGrado());
				System.out.println("================================================================================= \n");
			}
		}

	}
	public static int contador(List<Estudiante> estudiante) {
		int total = 1;
		for (int i = 0; i < estudiante.size(); i++) {
			try {
				if (Integer.parseInt(estudiante.get(i).getEdad()) >= 6 &&
						Integer.parseInt(estudiante.get(i).getEdad()) <= 10) {
					total++;
				}
			}catch (Exception e){
				System.out.println("Hubo un error con la edad");
			}
		}
		return total;
	}
	public static List<List<Estudiante>> separarPorGrados(List<Estudiante> estudiante){
		List<Estudiante> jardin = new ArrayList<>();
		List<Estudiante> primero = new ArrayList<>();
		List<Estudiante> segundo = new ArrayList<>();
		List<Estudiante> tercero = new ArrayList<>();
		List<Estudiante> cuarto = new ArrayList<>();
		List<Estudiante> quinto = new ArrayList<>();
		List<List<Estudiante>> estudiantes = new ArrayList<>();
		for (int i = 0; i < estudiante.size(); i++) {
			if (estudiante.get(i).getGrado().equalsIgnoreCase("Jardin")){
				jardin.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}else if (estudiante.get(i).getGrado().equalsIgnoreCase("Primero")){
				primero.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}else if (estudiante.get(i).getGrado().equalsIgnoreCase("Segundo")){
				segundo.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}else if (estudiante.get(i).getGrado().equalsIgnoreCase("Tercero")){
				tercero.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}else if (estudiante.get(i).getGrado().equalsIgnoreCase("Cuarto")){
				cuarto.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}else if (estudiante.get(i).getGrado().equalsIgnoreCase("Quinto")){
				quinto.add(new Estudiante(estudiante.get(i).getId(),estudiante.get(i).getNombre(),
						estudiante.get(i).getEdad(),estudiante.get(i).getGrado()));
			}

		}
		estudiantes.add(jardin);
		estudiantes.add(primero);
		estudiantes.add(segundo);
		estudiantes.add(tercero);
		estudiantes.add(cuarto);
		estudiantes.add(quinto);
		return estudiantes;
	}
}
